# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/ugorji/go
%global goipath         github.com/ugorji/go
Version:                1.2.6

%gometa

%global common_description %{expand:
Idiomatic codec and rpc lib for msgpack, cbor, json, etc. msgpack.org[Go].}

%global golicenses      LICENSE
%global godocs          FAQ.md README.md msgpack.org.md codec/README.md\\\
                        codec/bench/README.md codec/bench/bench.out.txt\\\
                        codec/codecgen/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Idiomatic codec and rpc lib for msgpack, cbor, json, etc. msgpack.org[Go]

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/tools/go/packages)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in codec/codecgen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc FAQ.md README.md msgpack.org.md codec/README.md codec/bench/README.md
%doc codec/bench/bench.out.txt codec/codecgen/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Jul 05 22:09:05 CEST 2021 Petr Menšík <pemensik@redhat.com> - 1.2.6-1
- Initial package

